Style/Tab:
  Enabled: false

Style/IndentationWidth:
  Enabled: false

Metrics/LineLength:
  Max: 120

StringLiterals:
  Enabled: false

AllCops:
  Exclude:
    - db/**/*
    - config/**/*

Style/EndOfLine:
  Enabled: false

Style/Documentation:
  Enabled: false