# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6fca3369e16c314e1548a2f2f236bbbb8bd72d0d4dda24ff9813270b9820d00f5eb78fcd5eb1ca119b0db63029c814eb299e8a375f75bbee0d981c728077e9a6

test:
  secret_key_base: dcef3d0f85aacc4bd4c06d02b2448ea96463384859853b2c6ab0f00c03d63e95629a050298f19d226ed558499d045578ac1420ae0d36d1e9a57f67bd66b1a55e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
